package com.interviewagent.aimock;

import static com.interviewagent.aimock.AiMockInterviewApi.*;
import static com.interviewagent.interview.InterviewApi.*;
import com.interviewagent.interview.InterviewService;
import static com.interviewagent.aimock.AiMockQuestionAgent.*;
import java.net.URI;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.sql.ResultSet;
import java.time.*;
import java.util.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

@Service
class AiMockInterviewService {
    private static final long MAX_AUDIO_BYTES = 10 * 1024 * 1024;
    private static final int MAX_TRANSCRIPT_CHARS = 40_000;
    private static final int LEGACY_QUESTION_LIMIT = 3;
    private final JdbcClient jdbc; private final InterviewService interviews; private final AiMockQuestionAgent questionAgent; private final AiMockStorage storage;
    private final String transcriptionUrl, transcriptionKey, transcriptionModel, volcengineSpeechKey;
    AiMockInterviewService(JdbcClient jdbc, InterviewService interviews, AiMockQuestionAgent questionAgent, AiMockStorage storage, @Value("${app.transcription.url:}") String transcriptionUrl, @Value("${app.transcription.api-key:}") String transcriptionKey, @Value("${app.transcription.model:}") String transcriptionModel, @Value("${VOLCENGINE_SPEECH_API_KEY:}") String volcengineSpeechKey) { this.jdbc = jdbc; this.interviews = interviews; this.questionAgent = questionAgent; this.storage = storage; this.transcriptionUrl = transcriptionUrl; this.transcriptionKey = transcriptionKey; this.transcriptionModel = transcriptionModel; this.volcengineSpeechKey = volcengineSpeechKey; }

    @Transactional Session create(String userId, StartRequest request) {
        String packageId = required(request.interviewPackageId(), "面试包");
        PackageInfo p = jdbc.sql("SELECT id, company, role, interview_round FROM interview_packages WHERE id=:id AND user_id=:user").param("id", packageId).param("user", userId).query((rs, row) -> new PackageInfo(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4))).optional().orElseThrow(AiMockInterviewService::notFound);
        Materials materials=materials(userId,p.id,p.company,p.role,p.round); String plan=questionAgent.serialize(questionAgent.plan(materials));
        String id = UUID.randomUUID().toString(); OffsetDateTime expires = OffsetDateTime.now();
        jdbc.sql("INSERT INTO ai_mock_interviews(id,user_id,interview_package_id,company,role,interview_round,status,expires_at,question_plan) VALUES(:id,:user,:package,:company,:role,:round,'RUNNING',:expires,:plan)").param("id",id).param("user",userId).param("package",packageId).param("company",p.company).param("role",p.role).param("round",p.round).param("expires",expires).param("plan",plan).update();
        addQuestion(userId, id, 0); return detail(userId,id);
    }
    Session active(String userId) { return jdbc.sql("SELECT id FROM ai_mock_interviews WHERE user_id=:user AND status IN ('RUNNING','TIME_EXPIRED') ORDER BY updated_at DESC LIMIT 1").param("user",userId).query(String.class).optional().map(id -> detail(userId,id)).orElseThrow(AiMockInterviewService::notFound); }
    Session get(String userId, String id) { return detail(userId,id); }

    @Transactional Session startAnswer(String userId, String id, String questionId) {
        session(userId,id); QuestionRow q=question(userId,id,questionId);
        if (!"OPEN".equals(q.state)) throw new IllegalArgumentException("当前题目不能开始回答。");
        jdbc.sql("UPDATE ai_mock_interview_questions SET answer_started_at=COALESCE(answer_started_at,CURRENT_TIMESTAMP),answer_expires_at=COALESCE(answer_expires_at,CURRENT_TIMESTAMP + INTERVAL '5' MINUTE),updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("id",questionId).update();
        return detail(userId,id);
    }
    @Transactional Session audio(String userId, String id, String questionId, MultipartFile file) {
        session(userId,id); QuestionRow q = question(userId,id,questionId);
        if (!"OPEN".equals(q.state)) throw new IllegalArgumentException("当前题目不能录音。");
        if (file == null || file.isEmpty()) throw new IllegalArgumentException("录音为空，请重新录音。");
        byte[] bytes; try { bytes=file.getBytes(); } catch(Exception e) { throw new IllegalArgumentException("读取录音失败，请重试。"); }
        String type = validateAudio(bytes);
        String asset = UUID.randomUUID().toString(), path="ai-mock/"+userId+"/"+asset+extension(type);
        storage.upload(path,type,bytes);
        try {
            jdbc.sql("INSERT INTO ai_mock_audio_assets(id,user_id,ai_mock_interview_id,question_id,original_filename,content_type,size_bytes,object_path,status) VALUES(:id,:user,:session,:question,:name,:type,:size,:path,'TRANSCRIBING')").param("id",asset).param("user",userId).param("session",id).param("question",questionId).param("name",safeName(file.getOriginalFilename())).param("type",type).param("size",bytes.length).param("path",path).update();
            jdbc.sql("UPDATE ai_mock_interview_questions SET state='TRANSCRIBING',updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("id",questionId).update();
            try { String transcript=limited(transcribe(userId,bytes,type),"转写文本",MAX_TRANSCRIPT_CHARS); String feedback=feedback(transcript,null); jdbc.sql("UPDATE ai_mock_audio_assets SET status='READY',transcript=:text,feedback=:feedback,updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("id",asset).param("text",transcript).param("feedback",feedback).update(); answer(userId,id,q,transcript); }
            catch (RuntimeException e) { String message=e.getMessage()==null?"转写失败，请重新录音。":e.getMessage(); jdbc.sql("UPDATE ai_mock_audio_assets SET status='FAILED',transcript_error=:error,updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("id",asset).param("error",message).update(); jdbc.sql("UPDATE ai_mock_interview_questions SET state='OPEN',updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("id",questionId).update(); }
            return detail(userId,id);
        } catch (RuntimeException e) {
            try { storage.delete(path); } catch (RuntimeException ignored) { }
            throw e;
        }
    }
    @Transactional Session confirm(String userId,String id,String questionId,ConfirmRequest request) {
        SessionRow s=session(userId,id); advanceExpiredQuestion(userId, id); QuestionRow q=question(userId,id,questionId); if ("ANSWERED".equals(q.state)) return detail(userId,id); if (!Set.of("OPEN","READY_TO_CONFIRM").contains(q.state)) throw new IllegalArgumentException("当前题目回答时间已结束，已进入下一题。");
        answer(userId,id,q,limited(required(request.answerText(),"确认文本"),"确认文本",MAX_TRANSCRIPT_CHARS));
        return detail(userId,id);
    }
    @Transactional Session finish(String userId,String id) {
        SessionRow s=session(userId,id); if (s.finalId != null) return detail(userId,id);
        List<QuestionRow> rows=questions(userId,id).stream().filter(q -> "ANSWERED".equals(q.state)).toList();
        var formal=interviews.createFromMock(userId,new InterviewRequest(s.company,s.role,s.round,OffsetDateTime.now(),s.packageId,"PENDING_REVIEW","UNKNOWN","AI 模拟面试记录，仅含用户确认的转写文本。"),rows.stream().map(q->new QuestionRequest(q.text,q.answer,"UNCERTAIN")).toList());
        jdbc.sql("UPDATE ai_mock_interviews SET status='FINISHED',final_interview_id=:final,finished_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND user_id=:user").param("final",formal.interview().id()).param("id",id).param("user",userId).update(); return detail(userId,id);
    }
    @Transactional void delete(String userId,String id) { SessionRow s=session(userId,id); for (AudioRow a:audioRows(id)) try { storage.delete(a.path); } catch(RuntimeException ignored) {} if(jdbc.sql("DELETE FROM ai_mock_interviews WHERE id=:id AND user_id=:user").param("id",id).param("user",userId).update()==0) throw notFound(); }
    ResponseEntity<byte[]> content(String userId,String audioId) { AudioRow a=audio(userId,audioId); if("DELETED".equals(a.status)) throw notFound(); return ResponseEntity.ok().contentType(MediaType.parseMediaType(a.type)).body(storage.download(a.path)); }
    @Transactional void deleteAudio(String userId,String audioId) { AudioRow a=audio(userId,audioId); storage.delete(a.path); jdbc.sql("DELETE FROM ai_mock_audio_assets WHERE id=:id AND user_id=:user").param("id",audioId).param("user",userId).update(); jdbc.sql("UPDATE ai_mock_interview_questions SET state='OPEN',updated_at=CURRENT_TIMESTAMP WHERE id=:id AND confirmed_answer_text=''").param("id",a.questionId).update(); }

    private void answer(String userId,String id,QuestionRow q,String text) { jdbc.sql("UPDATE ai_mock_interview_questions SET confirmed_answer_text=:answer,state='ANSWERED',updated_at=CURRENT_TIMESTAMP WHERE id=:id").param("answer",text).param("id",q.id).update(); SessionRow s=session(userId,id); if(q.sortOrder+1<questionLimit(s))addQuestion(userId,id,q.sortOrder+1); }
    private void addQuestion(String userId,String id,int order) { SessionRow s=session(userId,id); if(!"RUNNING".equals(s.status)||order>=questionLimit(s)) return; if(s.plan==null) return; List<QuestionRow> rows=questions(userId,id); QuestionDraft draft=questionAgent.generate(materials(userId,s.packageId,s.company,s.role,s.round),questionAgent.deserialize(s.plan).get(order),rows.stream().map(q->new QuestionHistory(q.text,q.type,q.competency,q.projectName,q.technology)).toList()); jdbc.sql("INSERT INTO ai_mock_interview_questions(id,ai_mock_interview_id,question_text,question_type,competency,project_name,technology,state,sort_order) VALUES(:id,:session,:text,:type,:competency,:project,:technology,'OPEN',:order)").param("id",UUID.randomUUID().toString()).param("session",id).param("text",draft.questionText()).param("type",draft.type()).param("competency",draft.competency()).param("project",draft.projectName()).param("technology",draft.technology()).param("order",order).update(); }
    private Materials materials(String userId,String packageId,String company,String role,String round) { String jd=jdbc.sql("SELECT jd.content FROM interview_packages p LEFT JOIN job_descriptions jd ON jd.id=p.job_description_id AND jd.user_id=:user WHERE p.id=:id AND p.user_id=:user").param("user",userId).param("id",packageId).query(String.class).optional().orElse("待补充"); String resume=jdbc.sql("SELECT COALESCE(rf.parsed_text,'待补充') FROM interview_packages p LEFT JOIN resume_files rf ON rf.id=p.resume_file_id AND rf.user_id=:user AND rf.parsed_status='READY' WHERE p.id=:id AND p.user_id=:user").param("user",userId).param("id",packageId).query(String.class).optional().orElse("待补充"); List<String> cards=jdbc.sql("SELECT c.project_name || '；背景与角色：' || c.background_and_role || '；目标与指标：' || c.goal_and_metrics || '；约束与取舍：' || c.constraints_and_tradeoffs || '；个人贡献：' || c.personal_contribution || '；结果与复盘：' || c.result_and_retrospective || '；适用题型：' || c.applicable_question_types FROM interview_package_evidence_cards l JOIN project_evidence_cards c ON c.id=l.evidence_card_id WHERE l.interview_package_id=:id AND c.user_id=:user").param("id",packageId).param("user",userId).query(String.class).list(); return new Materials(company,role,round,jd,resume,cards); }
    private String transcribe(String userId,byte[] bytes,String type) { return volcengineSpeechKey.isBlank() ? transcribeOpenAi(bytes,type) : transcribeVolcengine(userId,bytes,type); }
    private String transcribeVolcengine(String userId,byte[] bytes,String type) { if (!type.equals("audio/ogg") && !type.equals("audio/wav")) throw new IllegalStateException("豆包转写仅支持 OGG、WAV 或 MP3 音频；请使用支持 OGG 录音的浏览器，或手动填写文本。"); try { String body=new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(Map.of("user",Map.of("uid",userId),"audio",Map.of("data",Base64.getEncoder().encodeToString(bytes)),"request",Map.of("model_name","bigmodel","enable_itn",true,"enable_punc",true))); HttpResponse<String> r=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build().send(HttpRequest.newBuilder(URI.create("https://openspeech.bytedance.com/api/v3/auc/bigmodel/recognize/flash")).timeout(Duration.ofSeconds(60)).header("Content-Type","application/json").header("X-Api-Key",volcengineSpeechKey).header("X-Api-Resource-Id","volc.bigasr.auc_turbo").header("X-Api-Request-Id",UUID.randomUUID().toString()).header("X-Api-Sequence","-1").POST(HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString()); if(!"20000000".equals(r.headers().firstValue("X-Api-Status-Code").orElse(""))) throw new IllegalStateException("豆包转写请求失败；请检查服务已开通并手动填写文本。"); String text=new com.fasterxml.jackson.databind.ObjectMapper().readTree(r.body()).path("result").path("text").asText("").trim(); if(text.isBlank()) throw new IllegalStateException("豆包转写返回格式无效；请手动填写并确认回答文本。"); return text; } catch(IllegalStateException e){throw e;} catch(Exception e){throw new IllegalStateException("豆包转写超时或失败；请手动填写并确认回答文本。");} }
    private String transcribeOpenAi(byte[] bytes,String type) { if(transcriptionUrl.isBlank()||transcriptionKey.isBlank()||transcriptionModel.isBlank()) throw new IllegalStateException("转写服务尚未配置；请手动填写并确认回答文本。"); try { String boundary="----ai"+UUID.randomUUID(); byte[] body=("--"+boundary+"\r\nContent-Disposition: form-data; name=\"model\"\r\n\r\n"+transcriptionModel+"\r\n--"+boundary+"\r\nContent-Disposition: form-data; name=\"file\"; filename=\"answer\"\r\nContent-Type: "+type+"\r\n\r\n").getBytes(StandardCharsets.UTF_8); byte[] tail=("\r\n--"+boundary+"--\r\n").getBytes(StandardCharsets.UTF_8); byte[] all=new byte[body.length+bytes.length+tail.length]; System.arraycopy(body,0,all,0,body.length);System.arraycopy(bytes,0,all,body.length,bytes.length);System.arraycopy(tail,0,all,body.length+bytes.length,tail.length); HttpResponse<String> r=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build().send(HttpRequest.newBuilder(URI.create(transcriptionUrl)).timeout(Duration.ofSeconds(60)).header("Authorization","Bearer "+transcriptionKey).header("Content-Type","multipart/form-data; boundary="+boundary).POST(HttpRequest.BodyPublishers.ofByteArray(all)).build(),HttpResponse.BodyHandlers.ofString()); if(r.statusCode()/100!=2) throw new IllegalStateException("转写服务请求失败；请手动填写并确认回答文本。"); String text=new com.fasterxml.jackson.databind.ObjectMapper().readTree(r.body()).path("text").asText("").trim(); if(text.isBlank()) throw new IllegalStateException("转写返回格式无效；请手动填写并确认回答文本。"); return text; } catch(IllegalStateException e){throw e;} catch(Exception e){throw new IllegalStateException("转写超时或失败；请手动填写并确认回答文本。");} }
    private Session detail(String user,String id) { SessionRow s=session(user,id); advanceExpiredQuestion(user,id); s=session(user,id); List<QuestionRow> q=questions(user,id); return new Session(s.id,s.company,s.role,s.round,s.status,s.startedAt,s.finalId,questionLimit(s),q.stream().filter(x->Set.of("OPEN","TRANSCRIBING","READY_TO_CONFIRM").contains(x.state)).findFirst().map(x->apiQuestion(x,user)).orElse(null)); }
    private Question apiQuestion(QuestionRow q,String user) { return new Question(q.id,q.text,legacyType(q),q.competency,q.answer,q.state,q.sortOrder,q.answerExpiresAt,latestAudio(user,q.id)); }
    private Audio latestAudio(String user,String question) { return jdbc.sql("SELECT id,status,transcript,transcript_error,feedback,duration_ms FROM ai_mock_audio_assets WHERE user_id=:user AND question_id=:q ORDER BY created_at DESC LIMIT 1").param("user",user).param("q",question).query((rs,row)->new Audio(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),(Long)rs.getObject(6))).optional().orElse(null); }
    private void advanceExpiredQuestion(String user,String id) { List<QuestionRow> open=questions(user,id).stream().filter(q->Set.of("OPEN","TRANSCRIBING","READY_TO_CONFIRM").contains(q.state)).toList(); if(open.isEmpty() || open.getFirst().answerExpiresAt==null || OffsetDateTime.now().isBefore(open.getFirst().answerExpiresAt)) return; QuestionRow q=open.getFirst(); jdbc.sql("UPDATE ai_mock_interview_questions SET state='SKIPPED',updated_at=CURRENT_TIMESTAMP WHERE id=:id AND state IN ('OPEN','TRANSCRIBING','READY_TO_CONFIRM')").param("id",q.id).update(); SessionRow s=session(user,id); if(q.sortOrder+1<questionLimit(s))addQuestion(user,id,q.sortOrder+1); }
    private SessionRow session(String user,String id) { return jdbc.sql("SELECT id,interview_package_id,company,role,interview_round,status,started_at,expires_at,final_interview_id,question_plan FROM ai_mock_interviews WHERE id=:id AND user_id=:user").param("id",id).param("user",user).query((rs,row)->new SessionRow(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getObject(7,OffsetDateTime.class),rs.getObject(8,OffsetDateTime.class),rs.getString(9),rs.getString(10))).optional().orElseThrow(AiMockInterviewService::notFound); }
    private QuestionRow question(String user,String session,String id) { return questions(user,session).stream().filter(q->q.id.equals(id)).findFirst().orElseThrow(AiMockInterviewService::notFound); }
    private List<QuestionRow> questions(String user,String id) { session(user,id); return jdbc.sql("SELECT id,question_text,confirmed_answer_text,state,sort_order,answer_expires_at,question_type,competency,project_name,technology FROM ai_mock_interview_questions WHERE ai_mock_interview_id=:id ORDER BY sort_order").param("id",id).query((rs,row)->new QuestionRow(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getObject(6,OffsetDateTime.class),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10))).list(); }
    private AudioRow audio(String user,String id) { return jdbc.sql("SELECT id,question_id,object_path,content_type,status FROM ai_mock_audio_assets WHERE id=:id AND user_id=:user").param("id",id).param("user",user).query((rs,row)->new AudioRow(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5))).optional().orElseThrow(AiMockInterviewService::notFound); }
    private List<AudioRow> audioRows(String id) { return jdbc.sql("SELECT id,question_id,object_path,content_type,status FROM ai_mock_audio_assets WHERE ai_mock_interview_id=:id AND status<>'DELETED'").param("id",id).query((rs,row)->new AudioRow(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5))).list(); }
    private int questionLimit(SessionRow session) { return session.plan==null ? LEGACY_QUESTION_LIMIT : questionAgent.deserialize(session.plan).size(); }
    private static String legacyType(QuestionRow q) { return q.type!=null?q.type:q.sortOrder==0?"FUNDAMENTAL":q.sortOrder==1?"PROJECT":"SCENARIO"; }
    private static String audioType(byte[] b) { if(b.length>12&&b[0]=='R'&&b[1]=='I'&&b[2]=='F'&&b[3]=='F'&&b[8]=='W'&&b[9]=='A'&&b[10]=='V'&&b[11]=='E')return "audio/wav"; if(b.length>4&&b[0]=='O'&&b[1]=='g'&&b[2]=='g'&&b[3]=='S')return "audio/ogg"; if(b.length>4&&b[0]==0x1a&&b[1]==0x45&&b[2]==(byte)0xdf&&b[3]==(byte)0xa3)return "audio/webm"; if(b.length>12&&b[4]=='f'&&b[5]=='t'&&b[6]=='y'&&b[7]=='p')return "audio/mp4"; return null; }
    static String validateAudio(byte[] bytes) { if(bytes.length==0)throw new IllegalArgumentException("录音为空，请重新录音。"); if(bytes.length>MAX_AUDIO_BYTES)throw new IllegalArgumentException("录音超过 10 MiB，请缩短回答后重新录音。"); String type=audioType(bytes); if(type==null)throw new IllegalArgumentException("仅支持 WebM、Ogg、MP4 或 WAV 音频。"); return type; }
    private static String extension(String t){return t.endsWith("wav")?".wav":t.endsWith("ogg")?".ogg":t.endsWith("mp4")?".mp4":".webm";} private static String feedback(String text,Long duration){return "已确认文本 "+text.length()+" 字；当前转写结果不含词级时间戳，无法可靠计算语速、停顿或重复词。";} private static String safeName(String n){return n==null||n.isBlank()?"answer":n.replaceAll("[^\\p{L}\\p{N}._-]","_");} private static String required(String v,String l){if(v==null||v.trim().isBlank())throw new IllegalArgumentException(l+"不能为空。");return v.trim();} private static String limited(String value,String label,int maximum){if(value.length()>maximum)throw new IllegalArgumentException(label+"过长，请控制在 "+maximum+" 个字符以内。");return value;} private static NoSuchElementException notFound(){return new NoSuchElementException("资源不存在或无权访问。");}
    private record PackageInfo(String id,String company,String role,String round){} private record SessionRow(String id,String packageId,String company,String role,String round,String status,OffsetDateTime startedAt,OffsetDateTime expiresAt,String finalId,String plan){} private record QuestionRow(String id,String text,String answer,String state,int sortOrder,OffsetDateTime answerExpiresAt,String type,String competency,String projectName,String technology){} private record AudioRow(String id,String questionId,String path,String type,String status){}
}
